# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('access_token', models.CharField(max_length=100)),
                ('insta_id', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=50)),
                ('picture', models.CharField(max_length=200)),
            ],
        ),
    ]
