# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 09:35
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instagram', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('profile_picture', models.URLField(max_length=250)),
                ('full_name', models.CharField(max_length=100)),
                ('picture_url', models.URLField(max_length=250)),
                ('hashtag', models.CharField(max_length=50)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('search_count', models.IntegerField(default=0)),
                ('post_id', models.CharField(max_length=100)),
            ],
        ),
    ]
