# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='search_count',
            field=models.IntegerField(default=1),
        ),
    ]
