# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 09:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20160413_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=50)),
                ('search_count', models.IntegerField(default=1)),
                ('related_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='search_count',
        ),
    ]
