# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_auto_20160413_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='related_tags',
        ),
    ]
