# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_auto_20160416_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='related_tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.RelatedTag'),
        ),
    ]
