# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_hashtag_related_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='related_tags',
            new_name='related_tag',
        ),
    ]
