# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_auto_20160416_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='related_tag',
        ),
    ]
