# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0009_remove_hashtag_related_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedtag',
            name='related_hashtag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_tag', to='instagram.HashTag'),
        ),
    ]
